//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class General
    {
        public General()
        {
            this.ContactLists = new HashSet<ContactList>();
        }
    
        public int GId { get; set; }
        public string GPhoneNum { get; set; }
        public string RelationType { get; set; }
    
        public virtual ICollection<ContactList> ContactLists { get; set; }
    }
}
