//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationCM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<PersonalInfo> PersonalInfoes { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<ContactList> ContactLists { get; set; }
        public DbSet<BusinessContact> BusinessContacts { get; set; }
        public DbSet<General> Generals { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Help> Helps { get; set; }
        public DbSet<Email> Emails { get; set; }
    }
}
